# data
# dataset: "data_mine"
dataset: "data"
train_split: 0.85
n_buckets: 11
crop_up: 50
crop_down: 30
steering_correction: 0.2
image_size: [66, 200]
# image_size: [224, 224]
steering_std: 0.01
percent_zero: 0.1

# model

# training
lr: 0.001
batch_size: 32
epochs: 200
steps_per_epoch: 200
validation_steps: 10
